name: Build

on:
  pull_request:
  push:
    branches:
      - master

  jobs:
    detekt:
      runs-on: ubuntu-latest

      steps:
        - name: "Checkout the code"
          uses: actions/checkout@v2

        - name: "Run Detekt"
          uses: natiginfo/action-detekt-all@1.16.0-RC1
          with:
            args: --fail-fast --config config/detekt/config.yml

    build:
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout the code"
          uses: actions/checkout@v2
        - name: "Build the app"
          run: ./gradlew build